### ISSUE TITLE
Elternabend Verbesserung

### ISSUE THREAD

**Issue by roho-sqrt2** [schuleintern/Webportal#106]
Schön wäre es, wenn zum Bearbeiten der Slots nur die LuL angezeigt werden, die auch in den Klassen/Jgst., für die der Elternabend geplant wird, unterrichten.

**Comment by Spitschka** [comment]
Das halte ich für gefährlich, weil dann auch z.B. Schulpsychologen / Betreuungslehrer raus fallen würden.
