### ISSUE TITLE
Nachrichten: Manche Benutzer können nicht angeschrieben werden

### ISSUE THREAD

**Issue by roho-sqrt2** [schuleintern/Webportal#107]
Benutzer wie Bibliothekarin, Sozialpädagogin u.ä. können nicht als Adressat ausgewählt werden. Oder man steckt sie alle in den Topf "Verwaltung". Dann werden alle angeschrieben :-(

**Comment by Spitschka** [comment]
Das ist so gewollt. Wenn einzelne Personen kontaktierbar sein sollen, dann eine Gruppe mit dieser Person als Mitglied erstellen. Dort kann dann auch eingestellt werden, wer diese Gruppe kontaktieren darf.
