### ISSUE TITLE
Nachrichten: Anhänge werden gefressen

### ISSUE THREAD

**Issue by roho-sqrt2** [schuleintern/Webportal#110]
Jetzt ist es mir auch passiert (einige Kollegen haben davon schon berichtet):
Dateianhänge können ausgewählt werden

![Screenshot_2019-11-21 CSGintern - Carl-Spitzweg-Gymnasium](https://user-images.githubusercontent.com/56599759/69353581-00adee00-0c7f-11ea-99b3-c28c3e105bb5.png)

dann sieht man aber nur noch einen Papierkorb, keinen Dateinamen

![Screenshot_2019-11-21 CSGintern - Carl-Spitzweg-Gymnasium(1)](https://user-images.githubusercontent.com/56599759/69353650-20ddad00-0c7f-11ea-9bb3-33fada37fbc4.png)

Nach dem Versenden wurde auch kein Anhang übertragen.

Passiert wohl nicht bei pdf Dateiformat.
**Aber**: Ein Umbenennen bringt nix!

**Comment by Spitschka** [comment]
Umbennen bringt nix, weil er Mime Type prüft. Fehler ist gefixt.
