### ISSUE TITLE
Nachrichten (nur Schüler,  Eltern): Nachnamen werden nicht gefunden, Fehler

### ISSUE THREAD

**Issue by roho-sqrt2** [schuleintern/Webportal#122]
Adressaten (Eltern, Schüler) können aber über ihre Vornamen ausgewählt werden:
-----------------
![Screenshot_2020-01-07 CSGintern - Carl-Spitzweg-Gymnasium(1)](https://user-images.githubusercontent.com/56599759/71913506-d86b4780-3177-11ea-882a-3300b70bbd32.png)
-----------------
![Screenshot_2020-01-07 CSGintern - Carl-Spitzweg-Gymnasium(2)](https://user-images.githubusercontent.com/56599759/71913525-e02aec00-3177-11ea-8fd1-58ec81717086.png)

**Comment by chrisland** [comment]
danke. hab geschaut aber kein passendes issue  gefunden.

**Comment by chrisland** [comment]
fix: https://github.com/schuleintern/Webportal/pull/144

**Comment by chrisland** [comment]
doppelte issue: https://github.com/schuleintern/Webportal/issues/143
