### ISSUE TITLE
Checkbox auf iOS nicht auswählbar

### ISSUE THREAD

**Issue by Spitschka** [schuleintern/Webportal#124]
![image](https://user-images.githubusercontent.com/23582998/72139688-7f75fc00-338f-11ea-8896-c772c7fd123e.png)

**Comment by Spitschka** [comment]
Wahrscheinlich hilft ein Update von iCheck auf Version 2

**Comment by chrisland** [comment]
die version 2 ist doch auch schon etwas in die jahre gekommen:
https://github.com/fronteed/icheck/tree/2.x
für was wird das plugin den benötigt?
