### ISSUE TITLE
Benutzerverwaltung, Passwort-vergessen-Funktion inaktiv?

### ISSUE THREAD

**Issue by roho-sqrt2** [schuleintern/Webportal#131]
Voraussetzung:
Ein Schüler hat eine Mail-Adresse eingetragen und erhält auch Mails aus dem Portal.
Beobachtung:
Nach Betätigen der Passwort-vergessen-Funktion und Eingabe des Schlüssels erfolgt zwar der Hinweis, dass ein Mail zugeschickt wurde, das kommt aber nie an!?
Damit ist die Pwd-v-F nicht brauchbar und der Admin wird immer kontaktiert, wenn ein Schüler sein Pwd vergessen hat :-(

**Comment by chrisland** [comment]
https://github.com/schuleintern/Webportal/pull/140
