### ISSUE TITLE
Befreiung: Verbesserung

### ISSUE THREAD

**Issue by roho-sqrt2** [schuleintern/Webportal#135]
![Screenshot_2020-01-31 CSGintern - Carl-Spitzweg-Gymnasium](https://user-images.githubusercontent.com/56599759/73553076-a03ee800-4449-11ea-956d-a32e827e1af3.png)
Man muss hier den Zeitraum (U-Stunden) markieren können, für den befreit wird.
Z.B. wenn ein Schüler sich um 8:00 Uhr für den Nachmittagsunterricht befreien lässt.

**Comment by Spitschka** [comment]
Das wäre eine Beurlaubung.
