### ISSUE TITLE
Verbesserung: Gesendete Nachrichten in einen Ordner verschieben

### ISSUE THREAD

**Issue by roho-sqrt2** [schuleintern/Webportal#139]
Ich würde gerne gesendete Nachrichten (z.B. an eine bestimmte Klasse) aus Gründen der Übersichtlichkeit in einen  eigenen Ordner verschieben. Geht aber nicht :-)

**Comment by Spitschka** [comment]
Gesendete Nachrichten sind leider etwas besonders und deswegen leider nicht verschiebbar.
