### ISSUE TITLE
Verbesserung: leeren Stundenplan auswählen

### ISSUE THREAD

**Issue by roho-sqrt2** [schuleintern/Webportal#154]
Vor dem Beginn eines Schuljahres können die neuen ASV-Daten schon eingelesen werden, aber der Stundenplan ist evtl. noch nicht fertig und passt daher nicht. Es wird dann wahrscheinlich der alte den Eltern angezeigt, was zu Verwirrung führt.
In dem Fall wäre es schön, wenn einfach der initiale leere Stundenplan ausgewählt werden kann.

**Comment by Spitschka** [comment]
Beim Schuljahreswechsel, der vor dem ASV Import gemacht wird, wird ein leerer Stundenplan angelegt.
