### ISSUE TITLE
Fehler: mebis-Passwort

### ISSUE THREAD

**Issue by roho-sqrt2** [schuleintern/Webportal#181]
Das mebis-Passwort einer Schülerin aus der 5d wurde gleichlautend bei einer Schülerin aus der 7d eingetragen, die zufällig namensgleich mit der aus der 5 d ist. Der mebis-account der beiden unterscheidet sich aber!

**Comment by Spitschka** [comment]
Hallo, das lässt sich leider nicht verhindern, da es für die mebis Kennungen nur die Namen und Vornamen als Attribute gibt. Das Merkmal aus mebis liegt in SchuleIntern nicht vor.
