### ISSUE TITLE
Verbesserung: Reservierung/Ausleihe

### ISSUE THREAD

**Issue by roho-sqrt2** [schuleintern/Webportal#198]
Geräte usw. können für den gleichen Zeitrum mehrfach ausgeliehen werden. Im Bild wurde das Geräte Nr. 1 doppelt ausgeliehen.
Es wäre eine Verbesserung, wenn Geräte, die schon ausgeliehen wurden, gar nicht mehr zur Ausleihe zur Verfügung stünden.

![Bildschirmfoto vom 2020-12-04 16-02-19](https://user-images.githubusercontent.com/56599759/101179594-bc537d00-364a-11eb-88b4-f3e1481ebda5.png)

**Comment by chrisland** [comment]
ist in der kommende Version (ab 1.2.3) behoben
g
