### ISSUE TITLE
Namensänderung

### ISSUE THREAD

**Issue by TheresaRadulescu** [schuleintern/Webportal#257]
Kann man die Möglichkeit einbauen, die Namen der Kollegen ändern zu können? Nach Heirat muss man sonst in die Tabelle reinlangen, um den Anzeigenachnamen zu ändern.

**Comment by chrisland** [comment]
Die personenbezogenen Daten kommen alle aus dem ASV import und würden beim Import überschrieben werden.

**Comment by Spitschka** [comment]
Ich glaube es geht um die Nutzer. Der Nutzer zu einer Lehrkraft wird nach Namensänderung nicht umbenannt.
