### ISSUE TITLE
Webinstaller bauen

### ISSUE THREAD

**Issue by Spitschka** [schuleintern/Webportal#29]
Installation der Software über Upload von wenigen Dateien und Installation via Webinstaller.

**Comment by Spitschka** [comment]
In Arbeit.

**Comment by malibu4pprs** [comment]
Kommt! Ihr könnt doch nicht eine "einfache" Homepage lokal nicht umziehen können?
Also das ist eine der leichtessten Übungen!
Bei der DB kanns geringe Schwierigkeiten geben (zwecks Größe der Tabellen) aber da gibts Aus-/Umwege!
Die Tabellen der DB sind nett, aber manche zwangslos!! Zumindest für uns!

Um dieses Issue als "Große Verbesserung" anzusehen, dann Gute Nacht ...

**Comment by Spitschka** [comment]
Um was gehts genau? Werde nicht ganz schlau. Die PPRS ist schon lange umgezogen. Hier gehts um Neuinstallationen.

**Comment by malibu4pprs** [comment]
Hallo Herr Spitschka!

Lies einfach das Begehr!
Ich habe die ganze Seite auch schon lokal zum Laufen gebracht!

Also: Bei mir gibt's Null Probleme, aber deine Mitentwickler kommen wohl an Schwierigkeiten, äußerste Klimmzugschwierigkeiten!

Die Neuinstallation habe ich schon gesichert und für's neue Schuljahr vorbereitet!
Ich hoffe nur, Du hast das deinen Kunden auch geraten - eine Sicherungskopiue - stauts-quo -zu erstellen!

So nebenbei: Wenn nicht, dann Gute Nacht ... Der Herr Dirketor/Vorstand Dr. Rauch von der HVB nannte mich damals als den größten Hacker südlich und auch nördlich des Mains! Wenn du ihn triffst, dann richte ihm einen schönen Gruß von mir aus!

Also für mich/PPRS gibt's grade keine Probleme, nur mit der Tabelle "schule"!
Da sehe ich nur acht Schulen eingetragen, die mir doch noch nur in der Nachbarschaft sind! Absicht?
Oder wieviele Schulen können wir bei Begehrlichkeiten zwecks schule-intern kontaktieren ... uns zusammenschließen für eine gemeinsame Weiterentwicklung?!
Sind da wirklich/würglich nur 8 Schulen dabei?

Dann machen wir bei uns mal einen Kaffee-Klatsch! Und entwickeln mit meiner App-Gruppe
(wird schwierig hier, weil 2 Schüler*Innen hab ich schon in der finalen Runde des JwInfs, der nächste Bundeswettbewerb steht vor der Tür und im Informatik-Biber sind wir auch mehrfache Preisträger!)

Aber mach doch einfach eine Gruppe auf, in der "Was brauchen wir/Was will ich/Was können wir tun ... oder einfach eine 'Warum-nicht-Gruppe' " auf!
Ich habe gerade vorher meinem Sekretriat geschrieben, die in der Tabelle "schule" eingetragenen Schulen deren Direktor*innen meinem Direktor vorzuschlagen für einen kurzen Direktoren-Stammtisch in der Umgebung oder zu einem WebEx-Meeting!
Wenn das alle Schule sind, die Schule-Intern gebucht haben, dann Prima: 8 (in Worten acht) Schulen, die das Programm benutzen brauchen wollen, bayernweit ein Traum!

Spass beiseite: Das Programm ist Super, eigentlich ... mehre Anmerkungen gibt's später!

VLG
Marcus Lindwurm

________________________________

**Comment by Spitschka** [comment]
Hallo Marcus,
Die Schulen in "schulen" sind Schulen, von denen Schüler zu euch an die Schulen gekommen sind.
Wegen Austausch gerne. Können wir das ins Forum verlegen und nicht hier unter dem Ticket? 
LG, Christian

**Comment by Spitschka** [comment]
Installer ist im Github veröffentlicht.
