### ISSUE TITLE
(Test/Dummy) Benutzer (Lehrer,Schueler,...) im Adminpanel anlegen

### ISSUE THREAD

**Issue by chrisland** [schuleintern/Webportal#33]
Manuall/Admin-Interface Change DB Table "users" Colum "userNetwork"
mögliche Probleme:
- Asv-update ?

**Comment by Spitschka** [comment]
Ja, wird durch ASV Import wieder gelöscht, da ein Vollabgleich nötig wird. Lehrer müssen auch zwingend eine ASV ID (lokales Differenzierungsmerkmal) haben.
