### ISSUE TITLE
Kalender: Termin wird im Folgemonat nicht angezeigt

### ISSUE THREAD

**Issue by roho-sqrt2** [schuleintern/Webportal#72]
Wird im September ein Klassentermin eingetragen, der bis zu einem Datum im Oktober gehen soll, dann wird dieser Termin im Oktober (Folgemonat) im Klassenkalender nicht angezeigt. Im Kalender "Von mir eingetragen" ist der Folgemonat aber sichtbar!

**Comment by Spitschka** [comment]
Mit Version 1.1
