### ISSUE TITLE
Nachrichten: Empfänger wird in CC automatisch übernommen

### ISSUE THREAD

**Issue by roho-sqrt2** [schuleintern/Webportal#73]
Falls CC ausgewählt wird, erscheint automatisch im CC-Feld auch der Empfänger

**Comment by Spitschka** [comment]
Hast du da ein Beispiel? ich verstehe es gerade nicht. 🙈

**Comment by roho-sqrt2** [comment]
Ich wähle einen Empfänger aus, übernehme den mit "Ausgewählten Empfänger hinzufügen". Gehe dann auf Kopieempfänger und es erscheint unter CC der vorher ausgewählte Empfänger, was natürlich Unsinn ist. Man kann ihn zwar manuell löschen, aber ist das so gewollt?

**Comment by chrisland** [comment]
welcher Browser/Beriebssystem?
bei mit ff 69.0.2  osx 10.13.5 kann ich den fehler nicht reproduzieren.
welche empfanger wählst du aus? lehrer, eltern gruppen . und ich das immer so oder nur manchmal?

**Comment by roho-sqrt2** [comment]
Linux mit FF 68.1.0, Android mit FF
Ist (bei mir) immer so.
![Screenshot_2019-10-17 CSGintern - Carl-Spitzweg-Gymnasium](https://user-images.githubusercontent.com/56599759/67018344-63015500-f0fb-11e9-974f-da8fc30f0342.png)

**Comment by roho-sqrt2** [comment]
Habs gerade in einer VM ausprobiert: Win7 und FF gleiches Verhalten
Btw, man kann auch zuerst CC auswählen und dann den Empfänger. Emfänger ist durch CC schon vorbesetzt.
ODER: Ich hab einen kolossalen Workflow-Fehler ....

**Comment by Spitschka** [comment]
Ich kann das nicht nachvollziehen.

**Comment by Spitschka** [comment]
🤦‍♂ 🤦‍♂ 🤦‍♂ 🤦‍♂ 🤦‍♂ 🤦‍♂ 
Jetzt kapiere ich erst... Sorry. Ja, das ist falsch. Fehler anerkannt.

**Comment by roho-sqrt2** [comment]
Ufff ....
