### ISSUE TITLE
Kalender: Termin via ical abonnieren

### ISSUE THREAD

**Issue by roho-sqrt2** [schuleintern/Webportal#80]
Termine, die schon gelöscht wurden, erscheinen immer noch im Kalender "Meine Klassen (inkl. Exen)". Siehe doppelter Eintrag in den Screenshots (Thunderbird, Nextcloud).
![Bildschirmfoto vom 2019-10-18 16-32-05](https://user-images.githubusercontent.com/56599759/67103364-45002700-f1c5-11e9-8e88-356672419d07.png)
![Screenshot_2019-10-18 Kalender - Nextcloud](https://user-images.githubusercontent.com/56599759/67103365-4598bd80-f1c5-11e9-80ee-10e54660a76f.png)

**Comment by Spitschka** [comment]
Hier importierst du von SchuleIntern Richtung Nextcloud/Thunderbird?

**Comment by roho-sqrt2** [comment]
Ja. Gleiches Phänomen übrigens auch unter Android.
Hier das Original
![Screenshot_2019-10-24 CSGintern - Carl-Spitzweg-Gymnasium](https://user-images.githubusercontent.com/56599759/67497526-61e1a200-f67e-11e9-94f1-fdb39d6eefcd.png)

**Comment by Spitschka** [comment]
Danke. Bin auf der Fehlersuche.

**Comment by Spitschka** [comment]
Mit dem nächsten Update kommt da eine Änderung.
