### ISSUE TITLE
Schülerverwaltung > Schülerinfo > Unterricht: leere Liste

### ISSUE THREAD

**Issue by roho-sqrt2** [schuleintern/Webportal#83]
Nach dem Update erscheinen viele Kopplungen. Klickt man auf eine Kopplung (Z.B. Ethik), dann ist die Liste leer. In meiner Erinnerung war das vor dem Update anders.

**Comment by Spitschka** [comment]
An dieser Stelle wurde im Update nichts verändert. Hast du ein konkretes Beispiel? (Gerne auch per PM im Forum) LG

**Comment by roho-sqrt2** [comment]
Beispiel 5a: Es gibt keine 6 D-Kopplungen
Klickt man auf irgendeine Kopplung, dann erzeugt man immer eine leere Liste 

![Screenshot_2019-10-31 CSGintern - Carl-Spitzweg-Gymnasium(2)](https://user-images.githubusercontent.com/56599759/67987267-44d44280-fc2d-11e9-88e2-d80d0e823968.png)

**Comment by Spitschka** [comment]
Hallo Rolf, welche Kopplungen sollten da sein? Wird Ethik zusammen mit der 6D unterrichtet? Sind die Schüler den Unterrichten zugeordnet?

**Comment by roho-sqrt2** [comment]
Wie im Screenshot zu sehen: Die Ethik-Kopplung umfasst alle 5.Klassen. Die Schülerliste ist aber leer. genau das war schon anders, weil ich dieses Feature als Zugewinn "verkauft" habe: Der Ethik-Lehrer kann sich EINE Liste mit allen seinen Schülern erstellen.
In der ASV wurde an der Stelle nix geändert.

**Comment by roho-sqrt2** [comment]
Im Forum taucht das gleiche Problem auf:

https://www.schule-intern.de/forum/index.php?thread/69-keine-sch%C3%BCler-in-der-liste-der-unterrichte-bei-den-sch%C3%BClerinformationen/&postID=397#post397
