### ISSUE TITLE
Absenzen Sekretariat > Befreiung: Verbesserung

### ISSUE THREAD

**Issue by roho-sqrt2** [schuleintern/Webportal#85]
Wird ein Schüler befreit, dann wird auch aufgenommen, welcher Lehrer befreit hat, bzw. in wessen Unterrichtsstunde die Befreiung fällt. Im weiteren Verlauf wird diese Information nicht mehr angezeigt.
Später wäre es aber oft sinnvoll zu wissen, wer eigentlich (damals) den Schüler befreit hat.

**Comment by Spitschka** [comment]
Die Lehrkraft wird jetzt im Kommentar angezeigt.
