### ISSUE TITLE
MakeBackup.php - Über Kommandozeile steuerbar 

### ISSUE THREAD

**Issue by Spitschka** [schuleintern/Webportal#97]
Das Script MakeBackup.php sollte über CLI (nicht über $_GET) steuerbar sein, da es sich außerhalb des www Ordners befindet und wohl nur über Crons / SSH aufgerufen wird. (Beim Aufruf über die Shell hat das Script meist auch keine Laufzeitbeschränkung)

**Comment by chrisland** [comment]
cron laufen doch auch mit get parametern. hab jetzt ne weiche eingebaut und auch gleich die ausgabe auf der console angepasst.g

**Comment by Spitschka** [comment]
Danke!
Kannst du einen Pullrequest gegen Version1-1-0 stellen? Würde gerne den Master in der aktuellen Version 1.0.1 belassen.

**Comment by chrisland** [comment]
gerne.
habs umgestellt.
g

**Comment by Spitschka** [comment]
Close. Merged.
