### ISSUE TITLE
"cli" Ordner zum Update Prozess hinzufügen

### ISSUE THREAD

**Issue by chrisland** [schuleintern/Webportal#99]
sonst bleibt auch MakeBackup.php auf v1.0.0

**Comment by Spitschka** [comment]
Ups. Stimmt. 🤦‍♂ Wäre er dann in "framework" vielleicht besser aufgehoben?

**Comment by chrisland** [comment]
mh nö, ich find das ganz gut so separiert.
ist es aufwendig einen zweiten ordner mit in den update prozess aufzunehmen?
(sorry, hab grad das script nicht mehr im kopf)

**Comment by Spitschka** [comment]
Nein, nicht aufwändig. Ändere ich. 👍

**Comment by Spitschka** [comment]
Close.

**Comment by chrisland** [comment]
danke (-:
